### ISSUE TITLE
CLI Broken

### ISSUE THREAD

**Issue by tznind** [HicServices/BadMedicine#85]
**Describe the bug**

Looks like the current CLI is broken, possibly in the same way as BadMedicine.Dicom was (building multiple assemblies ontop of each other).

Running the current CLI gives this error:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at BadMedicine.Datasets.DataGenerator.EmbeddedCsvToDataTable(Type requestingType, String resourceFileName, DataTable dt)
   at BadMedicine.Datasets.BiochemistryRecord.Initialize() in /home/runner/work/BadMedicine/BadMedicine/BadMedicine.Core/Datasets/BiochemistryRecord.cs:line 105
   at BadMedicine.Datasets.BiochemistryRecord..ctor(Random r) in /home/runner/work/BadMedicine/BadMedicine/BadMedicine.Core/Datasets/BiochemistryRecord.cs:line 68
   at BadMedicine.Datasets.Biochemistry.GenerateTestDataRow(Person p) in /home/runner/work/BadMedicine/BadMedicine/BadMedicine.Core/Datasets/Biochemistry.cs:line 23
   at BadMedicine.Datasets.DataGenerator.GenerateTestDataFile(IPersonCollection cohort, FileInfo target, Int32 numberOfRecords) in /home/runner/work/BadMedicine/BadMedicine/BadMedicine.Core/Datasets/DataGenerator.cs:line 75
   at BadMedicine.Program.RunOptionsAndReturnExitCode(ProgramOptions opts) in /home/runner/work/BadMedicine/BadMedicine/BadMedicine/Program.cs:line 76
```

**Comment by tznind** [comment]
Yup now fixed in 1.0.1 release thanks
